"""Wave 1 of a DD in one command, everything in parallel. Target: the first read inside 60s.

    python3 dd.py <@handle | x.com link | CA | site>

Resolve: the X account's every post and X Article (articles never show in timeline APIs), the CA and
the site, from whichever of them was given (a bare CA gets its X and site from DexScreener).
Then at once:
  quick.py       market, copycats, who posts the CA, deployer age and %
  fomo_share.py  FOMO wallets' share of supply
  bundle.py      the launch bundle: what the deployer and first-slot buyers got vs hold now
  site           headers, CNAME, builder-platform fingerprint, GitHub and docs links
  programs       every Solana address in the site's HTML, JS and same-origin API that is an
                 executable program, with its upgrade authority
Sections print the moment they finish, each with its elapsed time. Articles go to data/dd/<handle>/.
"""
import json
import os
import re
import subprocess
import sys
import time
import urllib.parse
import urllib.request
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait

from quick import RPCS, socialdata
from sol import rpc

HERE = os.path.dirname(os.path.abspath(__file__))
UA = {"User-Agent": "Mozilla/5.0"}
B58_ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
B58 = re.compile(r"\b[1-9A-HJ-NP-Za-km-z]{32,44}\b")
EVM = re.compile(r"\b0x[a-fA-F0-9]{40}\b")
PLATFORMS = {"Lovable": r"lovable|gptengineer|data-lov-id", "v0": r"generated by v0|v0\.dev", "Framer": r"__framer|framer\.website",
             "Webflow": r"data-wf-site", "Replit": r"replit\.app|replit", "Bolt": r"bolt\.new|stackblitz", "Base44": r"base44",
             "Bubble": r"bubble\.io", "Carrd": r"carrd\.co", "Wix": r"wixstatic|wix\.com", "n8n": r"n8n\.cloud|/webhook/"}
T0 = time.time()


def fetch(url, timeout=15):
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=timeout) as r:
        return r.read().decode("utf-8", "replace"), dict(r.headers), r.url


def is_mint(a):
    v = rpc("getAccountInfo", [a, {"encoding": "jsonParsed"}])
    v = v and v.get("value")
    return bool(v) and isinstance(v["data"], dict) and v["data"].get("parsed", {}).get("type") == "mint"


def x_account(handle, u):
    """Every post and the full text of every X Article -> (report, texts to search for a CA, linked urls)."""
    posts, cursor = [], None
    for _ in range(5):  # 20 a page; 100 posts covers any fresh launch account
        page = socialdata(f"user/{u['id_str']}/tweets-and-replies", **({"cursor": cursor} if cursor else {}))
        posts += [t for t in page.get("tweets", []) if t["id_str"] not in {p["id_str"] for p in posts}]
        cursor = page.get("next_cursor")
        if not cursor or not page.get("tweets"):
            break

    def article(t):
        tw = json.load(urllib.request.urlopen(urllib.request.Request(
            f"https://api.fxtwitter.com/{handle}/status/{t['id_str']}", headers=UA), timeout=15)).get("tweet", {})
        a = tw.get("article")
        if not a:
            return None
        blocks = (a.get("content") or {}).get("blocks", [])
        return a.get("title"), "\n".join(b.get("text", "") for b in blocks) or a.get("preview_text", "")

    with ThreadPoolExecutor(10) as ex:
        arts = [x for x in ex.map(article, posts) if x]
    joined = time.strftime("%Y-%m-%d %H:%M UTC", time.strptime(u["created_at"][:19], "%Y-%m-%dT%H:%M:%S"))
    lines = [f"@{handle}: {u['followers_count']:,} followers, joined {joined}, {len(posts)} posts, {len(arts)} articles",
             f"  bio: {(u.get('description') or '').replace(chr(10), ' ')}", f"  url: {u.get('url') or '-'}"]
    for t in posts:
        lines.append(f"  {t['tweet_created_at'][:16]}  {t.get('views_count') or 0:>7} views  {t['full_text'][:280].replace(chr(10), ' ')}")
    d = f"{HERE}/data/dd/{handle}"
    os.makedirs(d, exist_ok=True)
    for title, body in arts:
        p = f"{d}/{re.sub(r'[^A-Za-z0-9]+', '-', title)[:60]}.md"
        open(p, "w").write(f"# {title}\n\n{body}\n")
        lines.append(f"  ARTICLE {title!r}: {len(body.split())} words -> {p}")
    texts = [*(t["full_text"] for t in posts), *(b for _, b in arts)]
    urls = [x.get("expanded_url", "") for t in posts for x in (t.get("entities") or {}).get("urls", [])]
    return "\n".join(lines), texts, urls


def socials(ca):
    """The project's X handle and site as DexScreener lists them, so a bare CA gets the full X and site checks."""
    pairs = _safe(lambda: json.loads(fetch(f"https://api.dexscreener.com/latest/dex/tokens/{ca}")[0]).get("pairs")) or []
    info = next((p["info"] for p in pairs if p.get("info")), {})
    x = next((s["url"] for s in info.get("socials", []) if s.get("type") == "twitter"), "")
    m = re.search(r"(?:x|twitter)\.com/([A-Za-z0-9_]+)", x)
    handle = m.group(1) if m and m.group(1) not in ("i", "search", "home", "intent") else None  # x.com/i/communities/...
    return handle, next((w["url"] for w in info.get("websites", [])), None)


def site_from(urls):
    site = next((x for x in urls if x and not re.search(r"(x|twitter)\.com", x)), None)
    return _safe(lambda: fetch(site)[2]) if site and "t.co/" in site else site


def resolve(arg):
    """-> handle, ca, site from whatever was given."""
    arg = arg.strip().lstrip("@")
    m = re.search(r"(?:x|twitter)\.com/([A-Za-z0-9_]+)", arg)
    if m:
        return m.group(1), None, None
    if B58.fullmatch(arg) or EVM.fullmatch(arg):
        return None, arg, None
    if "." in arg:
        return None, None, arg if arg.startswith("http") else f"https://{arg}"
    return arg, None, None


def ca_from(text):
    for a in dict.fromkeys(EVM.findall(text)):
        return a
    for a in dict.fromkeys(B58.findall(text)):
        if a.endswith("pump") or is_mint(a):
            return a


def site_check(site):
    html, headers, final = fetch(site)
    host = urllib.parse.urlparse(final).netloc
    cname = subprocess.run(["dig", "+short", "CNAME", host], capture_output=True, text=True).stdout.split()
    hits = [name for name, pat in PLATFORMS.items() if re.search(pat, html, re.I)]
    server = headers.get("server") or headers.get("Server") or "?"
    if "vercel" in server.lower() or "x-vercel-id" in {k.lower() for k in headers}:
        hits.append("Vercel host")
    title = re.search(r"<title>([^<]*)", html)
    links = sorted(set(re.findall(r'https?://(?:github\.com|x\.com|twitter\.com|t\.me|discord\.gg)/[^"\'\s<>)]+', html)))
    paths = sorted(set(re.findall(r'href="(/(?:docs|app)[^"#?]*)"', html)))
    lines = [f"SITE {final}  server {server}  CNAME {' '.join(cname) or '-'}",
             f"  title: {title.group(1) if title else '-'}",
             f"  platform: {', '.join(hits) if hits else 'custom (no builder fingerprint)'}",
             f"  links: {' '.join(links) or '-'}",
             f"  docs/app paths: {' '.join(paths[:25]) or '-'}"]
    return "\n".join(lines), html, final


def programs(html, base):
    """Executable Solana programs named anywhere in the site, its JS chunks or its same-origin API."""
    texts = [html]
    js = [urllib.parse.urljoin(base, s) for s in set(re.findall(r'src="(/_next/static/[^"]+\.js|/assets/[^"]+\.js)"', html))]
    docs = [urllib.parse.urljoin(base, p) for p in set(re.findall(r'href="(/docs[^"#?]*)"', html))]
    with ThreadPoolExecutor(10) as ex:
        texts += [t for t in ex.map(lambda u: _safe(lambda: fetch(u)[0]), js[:40] + docs[:25]) if t]
    api = {p.rstrip("/") for t in texts for p in re.findall(r'(/api/[A-Za-z0-9_/\-]+)', t)}
    api = sorted(api | {f"{p}/config" for p in api})[:30]  # an app API usually exposes its program IDs at /config
    with ThreadPoolExecutor(10) as ex:
        texts += [t for t in ex.map(lambda p: _safe(lambda: fetch(urllib.parse.urljoin(base, p), 8)[0]), api) if t]
    cands = sorted({a for t in texts for a in B58.findall(t) if _pubkey(a) and not a.startswith(("1111", "Token", "So111", "ATokenGP", "Sysvar", "ComputeBudget"))})
    found = []
    for i in range(0, len(cands), 100):
        # data sliced to 0 bytes: a big account in the batch would otherwise blow the response limit
        accts = rpc("getMultipleAccounts", [cands[i:i + 100], {"encoding": "base64", "dataSlice": {"offset": 0, "length": 0}}])["value"]
        found += [a for a, v in zip(cands[i:i + 100], accts) if v and v.get("executable")]
    lines = [f"PROGRAMS: {len(found)} executable of {len(cands)} addresses (HTML, {len(js)} JS, {len(api)} API paths: {' '.join(api) or '-'})"]
    for a in found:
        v = rpc("getAccountInfo", [a, {"encoding": "jsonParsed"}])["value"]
        info = (v["data"].get("parsed") or {}).get("info", {}) if isinstance(v["data"], dict) else {}
        auth = "immutable (non-upgradeable loader)"
        if info.get("programData"):
            pd = rpc("getAccountInfo", [info["programData"], {"encoding": "jsonParsed", "dataSlice": {"offset": 0, "length": 0}}])["value"]
            auth = (pd["data"].get("parsed") or {}).get("info", {}).get("authority") if isinstance(pd["data"], dict) else None
            auth = f"upgrade authority {auth}" if auth else "immutable (authority burned)"
            sigs = rpc("getSignaturesForAddress", [a, {"limit": 1000}])
            born = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime(sigs[-1]["blockTime"])) if sigs else "?"
            auth += f", deployed {born}, {len(sigs)}{'+' if len(sigs) == 1000 else ''} txs"
        lines.append(f"  {a}  {auth}")
    return "\n".join(lines)


def _pubkey(a):
    """Strict: exactly 32 bytes. Lenient decoders pad, so JS identifiers would pass and the RPC rejects the batch."""
    n = 0
    for ch in a:
        n = n * 58 + B58_ALPHABET.index(ch)
    return (len(a) - len(a.lstrip("1"))) + (n.bit_length() + 7) // 8 == 32


def _has_code(ca, chain):
    body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": "eth_getCode", "params": [ca, "latest"]}).encode()
    req = urllib.request.Request(RPCS[chain], body, {"Content-Type": "application/json", **UA})  # RH RPC 403s without a UA
    return _safe(lambda: json.load(urllib.request.urlopen(req, timeout=10))["result"] not in ("0x", None))


def _safe(f):
    try:
        return f()
    except Exception:
        return None


def script(*args, timeout=150):
    r = subprocess.run([sys.executable, *args], cwd=HERE, capture_output=True, text=True, timeout=timeout)
    return (r.stdout + r.stderr).strip()


def say(title, body):
    print(f"\n=== {title}  [{time.time() - T0:.0f}s]\n{body}", flush=True)


def main():
    handle, ca, site = resolve(sys.argv[1])
    # the profile alone (~1s) usually carries the CA and the site, so the chain and site checks start
    # from it while the posts and articles load
    if ca and not handle:
        handle, listed = socials(ca)
        site = site or listed
    u = _safe(lambda: socialdata(f"user/{handle}")) if handle else None
    u = u if u and u.get("id_str") else None
    if u:
        ca = ca or ca_from(u.get("description") or "")
        site = site or site_from([u.get("url")])
    html = final = None
    with ThreadPoolExecutor(8) as ex:
        jobs = {}

        def start_ca_jobs():
            jobs[ex.submit(script, "quick.py", ca)] = "QUICK"
            if ca.startswith("0x"):  # bundle.py is Solana-only; on EVM the deployer + holder scan is evm_relation
                for chain in [c for c in ("robinhood", "base") if _has_code(ca, c)]:
                    jobs[ex.submit(script, "evm_relation.py", ca, "--chain", chain)] = f"EVM {chain}"
                    jobs[ex.submit(script, "fomo_share.py", ca, "--chain", chain)] = f"FOMO {chain}"
            else:
                jobs[ex.submit(script, "bundle.py", ca)] = "BUNDLE"
                jobs[ex.submit(script, "fomo_share.py", ca)] = "FOMO"


        if u:
            jobs[ex.submit(x_account, handle, u)] = "X"
        if site:
            jobs[ex.submit(site_check, site)] = "SITE"
        if ca:
            start_ca_jobs()
        while jobs:
            done, _ = wait(jobs, return_when=FIRST_COMPLETED)
            for f in done:
                name = jobs.pop(f)
                try:
                    r = f.result()
                except Exception as e:
                    say(name, f"failed: {e}")
                    continue
                if name == "X":
                    r, texts, urls = r
                    if not ca:
                        ca = ca_from(" ".join(texts))
                        if ca:
                            say("CA", f"from the posts: {ca}")
                            start_ca_jobs()
                    if not site:
                        site = site_from(urls)
                        if site:
                            jobs[ex.submit(site_check, site)] = "SITE"
                if name == "SITE":
                    r, html, final = r
                    if not ca:
                        ca = ca_from(html)
                        say("CA", f"from the site: {ca}" if ca else "none on the site")
                        if ca:
                            start_ca_jobs()
                    if ca and not ca.startswith("0x"):
                        jobs[ex.submit(programs, html, final)] = "PROGRAMS"
                say(name, r)
    if not ca:
        say("CA", "none found in the bio, posts, articles or site")
    print(f"\nDONE [{time.time() - T0:.0f}s]  ca={ca}  site={site}")


if __name__ == "__main__":
    main()
